# SPDX-FileCopyrightText: 2022 - 2023 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx
    depends_on: [orthanc, orthanc-token-service]
    restart: unless-stopped
    ports: ["80:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
#    ports: ["443:443"]
#    volumes:
#      - /.../crt.pem:/etc/nginx/tls/crt.pem
#      - /.../key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"


  # first setup through configuration file and build step
  orthanc:
    image: osimis/orthanc:keycloak-unstable
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc.jsonc:/etc/orthanc/orthanc.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    env_file:
      - ./demo-setup/common-orthanc.env
    environment:
      VERBOSE_ENABLED: "true"

  orthanc-token-service:
    image: orthancteam/orthanc-token-service
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "share-password",
          "demo-script-user": "demo-script-password",
          "orthanc-oe2-user": "orthanc-oe2-password"
        }
      
  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports: ["8080:8080"]
    depends_on: [keycloak-db]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
    # in prod, replace "start-dev" by "start"
    command: "start-dev --proxy edge --hostname-path=/keycloak --hostname-strict=false"

  keycloak-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  orthanc-storage:
  orthanc-db:
  keycloak-db: