version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx
    depends_on: [orthanc-for-admin, orthanc-for-shares, orthanc-anonymizer, orthanc-token-service]
    restart: unless-stopped
    ports: ["80:80"]
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
#    ports: ["443:443"]
#    volumes:
#      - /.../crt.pem:/etc/nginx/tls/crt.pem
#      - /.../key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC_FOR_ADMIN: "true"
      ENABLE_ORTHANC_FOR_SHARES: "true"
      ENABLE_ORTHANC_FOR_ANON_SHARES: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "true"


  # first setup through configuration file and build step
  orthanc-for-admin:
    image: osimis/orthanc:master-unstable
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__ORTHANC_EXPLORER_2__SHARES__TYPE: "osimis-viewer-publication"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"


  orthanc-for-shares:
    image: osimis/orthanc:22.9.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-token-service:8000/shares/validate"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_IDENTIFIER: "standard-server-id"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USERNAME: "share-user"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD: "share-password"

  orthanc-for-anon-shares:
    image: osimis/orthanc:22.9.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for anon shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-token-service:8000/shares/validate"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_IDENTIFIER: "anonymized-server-id"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USERNAME: "share-user"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD: "share-password"

  orthanc-token-service:
    image: orthancteam/orthanc-token-service
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_ANONYMIZED_ORTHANC_ROOT: "http://localhost/anon-shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"
      SERVER_IDENTIFIER: "standard-server-id"
      ANONYMIZED_SERVER_IDENTIFIER: "anonymized-server-id"
      USERS: |
        {
          "share-user": "share-password",
          "demo-script-user": "demo-script-password",
          "orthanc-oe2-user": "orthanc-oe2-password"
        }
      TITLE_EXPIRED_TOKEN: "We are sorry to let you know that your token has expired.<br/>Please request a new token by sending us a mail."
      TITLE_INVALID_TOKEN: "We are sorry to let you know that your token is invalid.<br/>Please make sure you've copied it entirely."
      

  orthanc-share-landing:
    image: orthancteam/orthanc-share-landing
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_ANONYMIZED_ORTHANC_ROOT: "http://localhost/anon-shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"
      SERVER_IDENTIFIER: "standard-server-id"
      ANONYMIZED_SERVER_IDENTIFIER: "anonymized-server-id"

  orthanc-anonymizer:
    image: orthancteam/orthanc-anonymizer
    restart: unless-stopped
    environment:
      ORTHANC_ROOT: "http://orthanc-for-anon-shares:8042/"

  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage:
  orthanc-db:
