version: "3"
services:

  nginx:
    image: nginx:1.23-alpine
    volumes: ["./demo-setup/nginx.conf:/etc/nginx/conf.d/default.conf"]
    depends_on: [orthanc-for-admin, orthanc-for-shares, orthanc-anonymizer]
    restart: unless-stopped
    ports: ["80:80"]


  # first setup through configuration file and build step
  orthanc-for-admin:
    image: osimis/orthanc:22.6.4
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"


  orthanc-for-shares:
    image: osimis/orthanc:22.6.4
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-share:8000/shares/validate"

  orthanc-for-anon-shares:
    image: osimis/orthanc:22.6.4
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-anon-share:8000/shares/validate"

  orthanc-share:
    image: orthanc-team/orthanc-share
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"

  orthanc-anon-share:
    image: orthanc-team/orthanc-share
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8001:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key-for-anonymized-studies"
      PUBLIC_ORTHANC_ROOT: "http://localhost/anon-shares/"

  orthanc-anonymizer:
    image: orthanc-team/orthanc-anonymizer
    restart: unless-stopped
    environment:
      ORTHANC_ROOT: "http://orthanc-for-anon-shares:8042/"

  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage:
  orthanc-db:
