version: "3"
services:

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./demo-setup/nginx.orthanc.conf:/etc/nginx/conf.d/default.conf
    depends_on: [orthanc-for-admin, orthanc-for-shares, orthanc-anonymizer]
    restart: unless-stopped
    ports: ["80:80"]


  # first setup through configuration file and build step
  orthanc-for-admin:
    image: osimis/orthanc:22.9.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"


  orthanc-for-shares:
    image: osimis/orthanc:22.9.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-token-service:8000/shares/validate"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_IDENTIFIER: "standard-server-id"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USERNAME: "share-user"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD: "share-password"

  orthanc-for-anon-shares:
    image: osimis/orthanc:22.9.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/orthanc-db.jsonc:/etc/orthanc/orthanc-db.json
      - ./demo-setup/orthanc-share-auth.jsonc:/etc/orthanc/orthanc-share-auth.json
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for anon shares"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"

      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-token-service:8000/shares/validate"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_IDENTIFIER: "anonymized-server-id"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USERNAME: "share-user"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD: "share-password"

  orthanc-token-service:
    image: orthancteam/orthanc-token-service
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_ANONYMIZED_ORTHANC_ROOT: "http://localhost/anon-shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"
      SERVER_IDENTIFIER: "standard-server-id"
      ANONYMIZED_SERVER_IDENTIFIER: "anonymized-server-id"
      USERS: |
        {
          "share-user": "share-password",
          "demo-script-user": "demo-script-password",
          "orthanc-oe2-user": "orthanc-oe2-password"
        }
      

  orthanc-share-landing:
    image: orthancteam/orthanc-share-landing
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_ANONYMIZED_ORTHANC_ROOT: "http://localhost/anon-shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"
      SERVER_IDENTIFIER: "standard-server-id"
      ANONYMIZED_SERVER_IDENTIFIER: "anonymized-server-id"

  orthanc-anonymizer:
    image: orthancteam/orthanc-anonymizer
    restart: unless-stopped
    environment:
      ORTHANC_ROOT: "http://orthanc-for-anon-shares:8042/"

  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


volumes:
  orthanc-storage:
  orthanc-db:
