# SPDX-FileCopyrightText: 2022 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:22.11.3
    depends_on: [orthanc-for-admin, orthanc-for-shares, orthanc-token-service]
    restart: unless-stopped
    ports: ["80:80"]
    environment:
      ENABLE_ORTHANC_FOR_ADMIN: "true"
      ENABLE_ORTHANC_FOR_SHARES: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"

  orthanc-for-admin:
    image: osimis/orthanc:22.11.3
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC_JSON: |
        {
            "Name": "Orthanc for Admin",
            "OrthancExplorer2": {
                "IsDefaultUI": true,
                "UiOptions": {
                    "EnableShares": true,
                    "DefaultShareDuration": 0,
                    "ShareDurations": [0, 7, 15, 30, 90, 365]
                },
                "Shares" : {
                    "TokenService" : {
                        "Url": "http://orthanc-token-service:8000/shares"
                    },
                    "Type": "stone-viewer-publication",
                    "EnableStandardShares": true
                }
            },
            "RegisteredUsers": {
                "admin": "admin"
            }
        }

  orthanc-for-shares:
    image: osimis/orthanc:22.11.3
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on: [orthanc-db]
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "Orthanc for shares"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"

      # disable basic auth since we use the auth plugin
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__AUTHORIZATION__STANDARD_CONFIGURATIONS: |
        ["stone-webviewer"]
      ORTHANC__AUTHORIZATION__CHECKED_LEVEL: "studies"
      ORTHANC__AUTHORIZATION__WEB_SERVICE: "http://orthanc-token-service:8000/shares/validate"
      ORTHANC__AUTHORIZATION__TOKEN_GET_ARGUMENTS: |
        ["token"]

  orthanc-token-service:
    image: orthancteam/orthanc-token-service:22.11.3
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"

  orthanc-share-landing:
    image: orthancteam/orthanc-share-landing:22.11.3
    restart: unless-stopped
    environment:
      SECRET_KEY: "change-me-I-am-a-secret-key"
      PUBLIC_ORTHANC_ROOT: "http://localhost/shares/"
      PUBLIC_LANDING_ROOT: "http://localhost/welcome/"

  orthanc-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["orthanc-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-storage:
  orthanc-db:
